# Generated by Django 6.0.1 on 2026-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="is_publicated",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blogs/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
