# Generated by Django 6.0.1 on 2026-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_contacts_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="наименование"
            ),
        ),
    ]
