# Generated by Django 6.0.1 on 2026-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_in_stock",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
